// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for FileEntryKind.
const (
	Dir  FileEntryKind = "dir"
	File FileEntryKind = "file"
)

// Valid indicates whether the value is a known member of the FileEntryKind enum.
func (e FileEntryKind) Valid() bool {
	switch e {
	case Dir:
		return true
	case File:
		return true
	default:
		return false
	}
}

// Defines values for HerdrPaneSplitRequestDirection.
const (
	Down  HerdrPaneSplitRequestDirection = "down"
	Right HerdrPaneSplitRequestDirection = "right"
)

// Valid indicates whether the value is a known member of the HerdrPaneSplitRequestDirection enum.
func (e HerdrPaneSplitRequestDirection) Valid() bool {
	switch e {
	case Down:
		return true
	case Right:
		return true
	default:
		return false
	}
}

// Defines values for SearchResultType.
const (
	SearchResultTypeKnowledge SearchResultType = "knowledge"
	SearchResultTypeTask      SearchResultType = "task"
)

// Valid indicates whether the value is a known member of the SearchResultType enum.
func (e SearchResultType) Valid() bool {
	switch e {
	case SearchResultTypeKnowledge:
		return true
	case SearchResultTypeTask:
		return true
	default:
		return false
	}
}

// Defines values for TaskPriority.
const (
	High   TaskPriority = "high"
	Low    TaskPriority = "low"
	Medium TaskPriority = "medium"
	Urgent TaskPriority = "urgent"
)

// Valid indicates whether the value is a known member of the TaskPriority enum.
func (e TaskPriority) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	case Urgent:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	Blocked TaskStatus = "blocked"
	Doing   TaskStatus = "doing"
	Done    TaskStatus = "done"
	Review  TaskStatus = "review"
	Todo    TaskStatus = "todo"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Doing:
		return true
	case Done:
		return true
	case Review:
		return true
	case Todo:
		return true
	default:
		return false
	}
}

// Defines values for SearchParamsType.
const (
	SearchParamsTypeKnowledge SearchParamsType = "knowledge"
	SearchParamsTypeTask      SearchParamsType = "task"
)

// Valid indicates whether the value is a known member of the SearchParamsType enum.
func (e SearchParamsType) Valid() bool {
	switch e {
	case SearchParamsTypeKnowledge:
		return true
	case SearchParamsTypeTask:
		return true
	default:
		return false
	}
}

// CreateKnowledgeRequest defines model for CreateKnowledgeRequest.
type CreateKnowledgeRequest struct {
	Path string `json:"path"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Path string `json:"path"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Assignee *string       `json:"assignee,omitempty"`
	Due      *string       `json:"due,omitempty"`
	Name     string        `json:"name"`
	Priority *TaskPriority `json:"priority,omitempty"`
	Status   *TaskStatus   `json:"status,omitempty"`
	Tags     *[]string     `json:"tags,omitempty"`
}

// FileContent defines model for FileContent.
type FileContent struct {
	Content string `json:"content"`
	Path    string `json:"path"`
}

// FileEntry defines model for FileEntry.
type FileEntry struct {
	Kind FileEntryKind `json:"kind"`
	Name string        `json:"name"`
	Path string        `json:"path"`

	// Status Front matter status metadata for markdown files, if present
	Status *string `json:"status,omitempty"`
}

// FileEntryKind defines model for FileEntry.Kind.
type FileEntryKind string

// FilePathRequest defines model for FilePathRequest.
type FilePathRequest struct {
	Path string `json:"path"`
}

// GraphData defines model for GraphData.
type GraphData struct {
	Links []GraphLink `json:"links"`
	Nodes []GraphNode `json:"nodes"`
}

// GraphLink defines model for GraphLink.
type GraphLink struct {
	Source string `json:"source"`
	Target string `json:"target"`
}

// GraphNode defines model for GraphNode.
type GraphNode struct {
	Id    string  `json:"id"`
	Label string  `json:"label"`
	Type  *string `json:"type,omitempty"`
}

// HerdrAgent defines model for HerdrAgent.
type HerdrAgent struct {
	Cwd         *string `json:"cwd,omitempty"`
	Focused     *bool   `json:"focused,omitempty"`
	Name        string  `json:"name"`
	PaneId      string  `json:"pane_id"`
	Status      string  `json:"status"`
	Title       *string `json:"title,omitempty"`
	WorkspaceId string  `json:"workspace_id"`
}

// HerdrAgentSendKeysRequest defines model for HerdrAgentSendKeysRequest.
type HerdrAgentSendKeysRequest struct {
	Keys   []string `json:"keys"`
	Target string   `json:"target"`
}

// HerdrOpResponse defines model for HerdrOpResponse.
type HerdrOpResponse struct {
	Ok bool `json:"ok"`
}

// HerdrOverview defines model for HerdrOverview.
type HerdrOverview struct {
	Agents     []HerdrAgent     `json:"agents"`
	Available  bool             `json:"available"`
	Panes      []HerdrPane      `json:"panes"`
	Tabs       []HerdrTab       `json:"tabs"`
	Workspaces []HerdrWorkspace `json:"workspaces"`
}

// HerdrPane defines model for HerdrPane.
type HerdrPane struct {
	AgentStatus *string `json:"agent_status,omitempty"`
	Cwd         *string `json:"cwd,omitempty"`
	Focused     *bool   `json:"focused,omitempty"`
	PaneId      string  `json:"pane_id"`
	TabId       string  `json:"tab_id"`
	Title       *string `json:"title,omitempty"`
	WorkspaceId string  `json:"workspace_id"`
}

// HerdrPaneCloseRequest defines model for HerdrPaneCloseRequest.
type HerdrPaneCloseRequest struct {
	PaneId string `json:"pane_id"`
}

// HerdrPaneRenameRequest defines model for HerdrPaneRenameRequest.
type HerdrPaneRenameRequest struct {
	Label  string `json:"label"`
	PaneId string `json:"pane_id"`
}

// HerdrPaneSendKeysRequest defines model for HerdrPaneSendKeysRequest.
type HerdrPaneSendKeysRequest struct {
	Keys   []string `json:"keys"`
	PaneId string   `json:"pane_id"`
}

// HerdrPaneSendTextRequest defines model for HerdrPaneSendTextRequest.
type HerdrPaneSendTextRequest struct {
	PaneId string `json:"pane_id"`
	Text   string `json:"text"`
}

// HerdrPaneSplitRequest defines model for HerdrPaneSplitRequest.
type HerdrPaneSplitRequest struct {
	Cwd       *string                        `json:"cwd,omitempty"`
	Direction HerdrPaneSplitRequestDirection `json:"direction"`
	PaneId    string                         `json:"pane_id"`
}

// HerdrPaneSplitRequestDirection defines model for HerdrPaneSplitRequest.Direction.
type HerdrPaneSplitRequestDirection string

// HerdrPromptRequest defines model for HerdrPromptRequest.
type HerdrPromptRequest struct {
	Target string `json:"target"`
	Text   string `json:"text"`
}

// HerdrPromptResponse defines model for HerdrPromptResponse.
type HerdrPromptResponse struct {
	Ok bool `json:"ok"`
}

// HerdrReadRequest defines model for HerdrReadRequest.
type HerdrReadRequest struct {
	Target string `json:"target"`
}

// HerdrReadResponse defines model for HerdrReadResponse.
type HerdrReadResponse struct {
	Output string `json:"output"`
}

// HerdrTab defines model for HerdrTab.
type HerdrTab struct {
	AgentStatus *string `json:"agent_status,omitempty"`
	Focused     *bool   `json:"focused,omitempty"`
	Label       string  `json:"label"`
	Number      *int    `json:"number,omitempty"`
	PaneCount   *int    `json:"pane_count,omitempty"`
	TabId       string  `json:"tab_id"`
	WorkspaceId string  `json:"workspace_id"`
}

// HerdrTabCloseRequest defines model for HerdrTabCloseRequest.
type HerdrTabCloseRequest struct {
	TabId string `json:"tab_id"`
}

// HerdrTabCreateRequest defines model for HerdrTabCreateRequest.
type HerdrTabCreateRequest struct {
	Cwd   *string `json:"cwd,omitempty"`
	Label *string `json:"label,omitempty"`

	// Project Project name. When no herdr workspace has this label, the project's first workspace (cwd of the project) is bootstrapped and its root tab carries the requested label.
	Project     *string `json:"project,omitempty"`
	WorkspaceId *string `json:"workspace_id,omitempty"`
}

// HerdrTabRenameRequest defines model for HerdrTabRenameRequest.
type HerdrTabRenameRequest struct {
	Label string `json:"label"`
	TabId string `json:"tab_id"`
}

// HerdrWorkspace defines model for HerdrWorkspace.
type HerdrWorkspace struct {
	AgentStatus string `json:"agent_status"`
	Focused     *bool  `json:"focused,omitempty"`
	Label       string `json:"label"`
	Number      *int   `json:"number,omitempty"`
	PaneCount   *int   `json:"pane_count,omitempty"`
	TabCount    *int   `json:"tab_count,omitempty"`
	WorkspaceId string `json:"workspace_id"`
}

// Knowledge defines model for Knowledge.
type Knowledge struct {
	Aliases   *[]string  `json:"aliases,omitempty"`
	Body      *string    `json:"body,omitempty"`
	Created   *time.Time `json:"created,omitempty"`
	Lastmod   *time.Time `json:"lastmod,omitempty"`
	Path      string     `json:"path"`
	Tags      *[]string  `json:"tags,omitempty"`
	Title     string     `json:"title"`
	Type      *string    `json:"type,omitempty"`
	WikiLinks *[]string  `json:"wiki_links,omitempty"`
}

// KnowledgeContent defines model for KnowledgeContent.
type KnowledgeContent struct {
	Content string `json:"content"`
	Path    string `json:"path"`
}

// Meta defines model for Meta.
type Meta struct {
	DefaultProject string   `json:"default_project"`
	Favorites      []string `json:"favorites"`
	Project        string   `json:"project"`
	Projects       []string `json:"projects"`
	RecentFiles    []string `json:"recent_files"`
	Tags           []string `json:"tags"`
}

// MoveFileRequest defines model for MoveFileRequest.
type MoveFileRequest struct {
	NewPath string `json:"new_path"`
	OldPath string `json:"old_path"`
}

// MoveKnowledgeRequest defines model for MoveKnowledgeRequest.
type MoveKnowledgeRequest struct {
	NewPath string `json:"new_path"`
	OldPath string `json:"old_path"`
}

// Project defines model for Project.
type Project struct {
	Name string `json:"name"`
	Path string `json:"path"`
}

// ProjectGitStatus defines model for ProjectGitStatus.
type ProjectGitStatus struct {
	// Dirty Whether the project has any uncommitted changes
	Dirty bool `json:"dirty"`

	// Modified Number of modified files
	Modified int `json:"modified"`

	// Staged Number of staged files
	Staged int `json:"staged"`

	// Untracked Number of untracked files
	Untracked int `json:"untracked"`
}

// RecordRecentRequest defines model for RecordRecentRequest.
type RecordRecentRequest struct {
	Path string `json:"path"`
}

// RenameKnowledgeRequest defines model for RenameKnowledgeRequest.
type RenameKnowledgeRequest struct {
	NewName string `json:"new_name"`
	OldPath string `json:"old_path"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Id      *string          `json:"id,omitempty"`
	Path    string           `json:"path"`
	Snippet *string          `json:"snippet,omitempty"`
	Title   string           `json:"title"`
	Type    SearchResultType `json:"type"`
}

// SearchResultType defines model for SearchResult.Type.
type SearchResultType string

// Task defines model for Task.
type Task struct {
	Archived      *bool        `json:"archived,omitempty"`
	Assignee      *string      `json:"assignee,omitempty"`
	Body          *string      `json:"body,omitempty"`
	Created       *time.Time   `json:"created,omitempty"`
	Due           *string      `json:"due,omitempty"`
	Id            string       `json:"id"`
	PendingReason *string      `json:"pending_reason,omitempty"`
	PendingUntil  *string      `json:"pending_until,omitempty"`
	Priority      TaskPriority `json:"priority"`
	Project       *string      `json:"project,omitempty"`
	Status        TaskStatus   `json:"status"`
	Tags          *[]string    `json:"tags,omitempty"`
	Title         string       `json:"title"`
}

// TaskPriority defines model for TaskPriority.
type TaskPriority string

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// UpdateFavoriteRequest defines model for UpdateFavoriteRequest.
type UpdateFavoriteRequest struct {
	Enabled bool   `json:"enabled"`
	Path    string `json:"path"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Assignee *string       `json:"assignee,omitempty"`
	Due      *string       `json:"due,omitempty"`
	Name     *string       `json:"name,omitempty"`
	Priority *TaskPriority `json:"priority,omitempty"`
	Status   *TaskStatus   `json:"status,omitempty"`
	Tags     *[]string     `json:"tags,omitempty"`
}

// GetFileContentParams defines parameters for GetFileContent.
type GetFileContentParams struct {
	Path string `form:"path" json:"path"`
}

// GetGraphParams defines parameters for GetGraph.
type GetGraphParams struct {
	// Path Optional root directory to scope the graph to (empty means the whole project)
	Path *string `form:"path,omitempty" json:"path,omitempty"`
}

// ListKnowledgeParams defines parameters for ListKnowledge.
type ListKnowledgeParams struct {
	Path *string `form:"path,omitempty" json:"path,omitempty"`
	Tag  *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// GetKnowledgeContentParams defines parameters for GetKnowledgeContent.
type GetKnowledgeContentParams struct {
	Path string `form:"path" json:"path"`
}

// GetProjectPathsParams defines parameters for GetProjectPaths.
type GetProjectPathsParams struct {
	Prefix *string `form:"prefix,omitempty" json:"prefix,omitempty"`
}

// SearchParams defines parameters for Search.
type SearchParams struct {
	Q    string            `form:"q" json:"q"`
	Type *SearchParamsType `form:"type,omitempty" json:"type,omitempty"`
}

// SearchParamsType defines parameters for Search.
type SearchParamsType string

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	All    *bool   `form:"all,omitempty" json:"all,omitempty"`
	Status *string `form:"status,omitempty" json:"status,omitempty"`
	Tag    *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// CreateFileJSONRequestBody defines body for CreateFile for application/json ContentType.
type CreateFileJSONRequestBody = FilePathRequest

// SaveFileContentJSONRequestBody defines body for SaveFileContent for application/json ContentType.
type SaveFileContentJSONRequestBody = FileContent

// CopyFileJSONRequestBody defines body for CopyFile for application/json ContentType.
type CopyFileJSONRequestBody = MoveFileRequest

// DeleteFileJSONRequestBody defines body for DeleteFile for application/json ContentType.
type DeleteFileJSONRequestBody = FilePathRequest

// MoveFileJSONRequestBody defines body for MoveFile for application/json ContentType.
type MoveFileJSONRequestBody = MoveFileRequest

// PromptHerdrAgentJSONRequestBody defines body for PromptHerdrAgent for application/json ContentType.
type PromptHerdrAgentJSONRequestBody = HerdrPromptRequest

// ReadHerdrAgentJSONRequestBody defines body for ReadHerdrAgent for application/json ContentType.
type ReadHerdrAgentJSONRequestBody = HerdrReadRequest

// SendKeysHerdrAgentJSONRequestBody defines body for SendKeysHerdrAgent for application/json ContentType.
type SendKeysHerdrAgentJSONRequestBody = HerdrAgentSendKeysRequest

// CloseHerdrPaneJSONRequestBody defines body for CloseHerdrPane for application/json ContentType.
type CloseHerdrPaneJSONRequestBody = HerdrPaneCloseRequest

// ReadHerdrPaneJSONRequestBody defines body for ReadHerdrPane for application/json ContentType.
type ReadHerdrPaneJSONRequestBody = HerdrReadRequest

// RenameHerdrPaneJSONRequestBody defines body for RenameHerdrPane for application/json ContentType.
type RenameHerdrPaneJSONRequestBody = HerdrPaneRenameRequest

// SendKeysHerdrPaneJSONRequestBody defines body for SendKeysHerdrPane for application/json ContentType.
type SendKeysHerdrPaneJSONRequestBody = HerdrPaneSendKeysRequest

// SendTextHerdrPaneJSONRequestBody defines body for SendTextHerdrPane for application/json ContentType.
type SendTextHerdrPaneJSONRequestBody = HerdrPaneSendTextRequest

// SplitHerdrPaneJSONRequestBody defines body for SplitHerdrPane for application/json ContentType.
type SplitHerdrPaneJSONRequestBody = HerdrPaneSplitRequest

// CloseHerdrTabJSONRequestBody defines body for CloseHerdrTab for application/json ContentType.
type CloseHerdrTabJSONRequestBody = HerdrTabCloseRequest

// CreateHerdrTabJSONRequestBody defines body for CreateHerdrTab for application/json ContentType.
type CreateHerdrTabJSONRequestBody = HerdrTabCreateRequest

// RenameHerdrTabJSONRequestBody defines body for RenameHerdrTab for application/json ContentType.
type RenameHerdrTabJSONRequestBody = HerdrTabRenameRequest

// CreateKnowledgeJSONRequestBody defines body for CreateKnowledge for application/json ContentType.
type CreateKnowledgeJSONRequestBody = CreateKnowledgeRequest

// SaveKnowledgeContentJSONRequestBody defines body for SaveKnowledgeContent for application/json ContentType.
type SaveKnowledgeContentJSONRequestBody = KnowledgeContent

// MoveKnowledgeJSONRequestBody defines body for MoveKnowledge for application/json ContentType.
type MoveKnowledgeJSONRequestBody = MoveKnowledgeRequest

// RenameKnowledgeJSONRequestBody defines body for RenameKnowledge for application/json ContentType.
type RenameKnowledgeJSONRequestBody = RenameKnowledgeRequest

// UpdateFavoriteJSONRequestBody defines body for UpdateFavorite for application/json ContentType.
type UpdateFavoriteJSONRequestBody = UpdateFavoriteRequest

// RecordRecentJSONRequestBody defines body for RecordRecent for application/json ContentType.
type RecordRecentJSONRequestBody = RecordRecentRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest
