// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for FileEntryKind.
const (
	Dir  FileEntryKind = "dir"
	File FileEntryKind = "file"
)

// Valid indicates whether the value is a known member of the FileEntryKind enum.
func (e FileEntryKind) Valid() bool {
	switch e {
	case Dir:
		return true
	case File:
		return true
	default:
		return false
	}
}

// Defines values for SearchResultType.
const (
	SearchResultTypeKnowledge SearchResultType = "knowledge"
	SearchResultTypeTask      SearchResultType = "task"
)

// Valid indicates whether the value is a known member of the SearchResultType enum.
func (e SearchResultType) Valid() bool {
	switch e {
	case SearchResultTypeKnowledge:
		return true
	case SearchResultTypeTask:
		return true
	default:
		return false
	}
}

// Defines values for TaskPriority.
const (
	High   TaskPriority = "high"
	Low    TaskPriority = "low"
	Medium TaskPriority = "medium"
	Urgent TaskPriority = "urgent"
)

// Valid indicates whether the value is a known member of the TaskPriority enum.
func (e TaskPriority) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	case Urgent:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	Blocked TaskStatus = "blocked"
	Doing   TaskStatus = "doing"
	Done    TaskStatus = "done"
	Review  TaskStatus = "review"
	Todo    TaskStatus = "todo"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Doing:
		return true
	case Done:
		return true
	case Review:
		return true
	case Todo:
		return true
	default:
		return false
	}
}

// Defines values for SearchParamsType.
const (
	SearchParamsTypeKnowledge SearchParamsType = "knowledge"
	SearchParamsTypeTask      SearchParamsType = "task"
)

// Valid indicates whether the value is a known member of the SearchParamsType enum.
func (e SearchParamsType) Valid() bool {
	switch e {
	case SearchParamsTypeKnowledge:
		return true
	case SearchParamsTypeTask:
		return true
	default:
		return false
	}
}

// CreateKnowledgeRequest defines model for CreateKnowledgeRequest.
type CreateKnowledgeRequest struct {
	Path string `json:"path"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Assignee *string       `json:"assignee,omitempty"`
	Due      *string       `json:"due,omitempty"`
	Name     string        `json:"name"`
	Priority *TaskPriority `json:"priority,omitempty"`
	Status   *TaskStatus   `json:"status,omitempty"`
	Tags     *[]string     `json:"tags,omitempty"`
}

// FileContent defines model for FileContent.
type FileContent struct {
	Content string `json:"content"`
	Path    string `json:"path"`
}

// FileEntry defines model for FileEntry.
type FileEntry struct {
	Kind FileEntryKind `json:"kind"`
	Name string        `json:"name"`
	Path string        `json:"path"`
}

// FileEntryKind defines model for FileEntry.Kind.
type FileEntryKind string

// GraphData defines model for GraphData.
type GraphData struct {
	Links []GraphLink `json:"links"`
	Nodes []GraphNode `json:"nodes"`
}

// GraphLink defines model for GraphLink.
type GraphLink struct {
	Source string `json:"source"`
	Target string `json:"target"`
}

// GraphNode defines model for GraphNode.
type GraphNode struct {
	Id    string  `json:"id"`
	Label string  `json:"label"`
	Type  *string `json:"type,omitempty"`
}

// Knowledge defines model for Knowledge.
type Knowledge struct {
	Aliases   *[]string  `json:"aliases,omitempty"`
	Body      *string    `json:"body,omitempty"`
	Created   *time.Time `json:"created,omitempty"`
	Lastmod   *time.Time `json:"lastmod,omitempty"`
	Path      string     `json:"path"`
	Tags      *[]string  `json:"tags,omitempty"`
	Title     string     `json:"title"`
	Type      *string    `json:"type,omitempty"`
	WikiLinks *[]string  `json:"wiki_links,omitempty"`
}

// KnowledgeContent defines model for KnowledgeContent.
type KnowledgeContent struct {
	Content string `json:"content"`
	Path    string `json:"path"`
}

// Meta defines model for Meta.
type Meta struct {
	DefaultProject string   `json:"default_project"`
	Favorites      []string `json:"favorites"`
	Project        string   `json:"project"`
	Projects       []string `json:"projects"`
	RecentFiles    []string `json:"recent_files"`
	Tags           []string `json:"tags"`
}

// MoveFileRequest defines model for MoveFileRequest.
type MoveFileRequest struct {
	NewPath string `json:"new_path"`
	OldPath string `json:"old_path"`
}

// MoveKnowledgeRequest defines model for MoveKnowledgeRequest.
type MoveKnowledgeRequest struct {
	NewPath string `json:"new_path"`
	OldPath string `json:"old_path"`
}

// RecordRecentRequest defines model for RecordRecentRequest.
type RecordRecentRequest struct {
	Path string `json:"path"`
}

// RenameKnowledgeRequest defines model for RenameKnowledgeRequest.
type RenameKnowledgeRequest struct {
	NewName string `json:"new_name"`
	OldPath string `json:"old_path"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Id      *string          `json:"id,omitempty"`
	Path    string           `json:"path"`
	Snippet *string          `json:"snippet,omitempty"`
	Title   string           `json:"title"`
	Type    SearchResultType `json:"type"`
}

// SearchResultType defines model for SearchResult.Type.
type SearchResultType string

// Task defines model for Task.
type Task struct {
	Archived *bool        `json:"archived,omitempty"`
	Assignee *string      `json:"assignee,omitempty"`
	Body     *string      `json:"body,omitempty"`
	Created  *time.Time   `json:"created,omitempty"`
	Due      *string      `json:"due,omitempty"`
	Id       string       `json:"id"`
	Priority TaskPriority `json:"priority"`
	Project  *string      `json:"project,omitempty"`
	Status   TaskStatus   `json:"status"`
	Tags     *[]string    `json:"tags,omitempty"`
	Title    string       `json:"title"`
}

// TaskPriority defines model for TaskPriority.
type TaskPriority string

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// UpdateFavoriteRequest defines model for UpdateFavoriteRequest.
type UpdateFavoriteRequest struct {
	Enabled bool   `json:"enabled"`
	Path    string `json:"path"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Assignee *string       `json:"assignee,omitempty"`
	Due      *string       `json:"due,omitempty"`
	Name     *string       `json:"name,omitempty"`
	Priority *TaskPriority `json:"priority,omitempty"`
	Status   *TaskStatus   `json:"status,omitempty"`
	Tags     *[]string     `json:"tags,omitempty"`
}

// GetFileContentParams defines parameters for GetFileContent.
type GetFileContentParams struct {
	Path string `form:"path" json:"path"`
}

// ListKnowledgeParams defines parameters for ListKnowledge.
type ListKnowledgeParams struct {
	Path *string `form:"path,omitempty" json:"path,omitempty"`
	Tag  *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// GetKnowledgeContentParams defines parameters for GetKnowledgeContent.
type GetKnowledgeContentParams struct {
	Path string `form:"path" json:"path"`
}

// SearchParams defines parameters for Search.
type SearchParams struct {
	Q    string            `form:"q" json:"q"`
	Type *SearchParamsType `form:"type,omitempty" json:"type,omitempty"`
}

// SearchParamsType defines parameters for Search.
type SearchParamsType string

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	All    *bool   `form:"all,omitempty" json:"all,omitempty"`
	Status *string `form:"status,omitempty" json:"status,omitempty"`
	Tag    *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// SaveFileContentJSONRequestBody defines body for SaveFileContent for application/json ContentType.
type SaveFileContentJSONRequestBody = FileContent

// MoveFileJSONRequestBody defines body for MoveFile for application/json ContentType.
type MoveFileJSONRequestBody = MoveFileRequest

// CreateKnowledgeJSONRequestBody defines body for CreateKnowledge for application/json ContentType.
type CreateKnowledgeJSONRequestBody = CreateKnowledgeRequest

// SaveKnowledgeContentJSONRequestBody defines body for SaveKnowledgeContent for application/json ContentType.
type SaveKnowledgeContentJSONRequestBody = KnowledgeContent

// MoveKnowledgeJSONRequestBody defines body for MoveKnowledge for application/json ContentType.
type MoveKnowledgeJSONRequestBody = MoveKnowledgeRequest

// RenameKnowledgeJSONRequestBody defines body for RenameKnowledge for application/json ContentType.
type RenameKnowledgeJSONRequestBody = RenameKnowledgeRequest

// UpdateFavoriteJSONRequestBody defines body for UpdateFavorite for application/json ContentType.
type UpdateFavoriteJSONRequestBody = UpdateFavoriteRequest

// RecordRecentJSONRequestBody defines body for RecordRecent for application/json ContentType.
type RecordRecentJSONRequestBody = RecordRecentRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest
