server {
    listen 10443 ssl;

    ssl_certificate "/etc/nginx/ssl/server.pem";
    ssl_certificate_key "/etc/nginx/ssl/server-key.pem";
    # ssl_session_cache shared:SSL:1m;
    # ssl_session_timeout  10m;
    # ssl_ciphers HIGH:!aNULL:!MD5;
    # ssl_prefer_server_ciphers on;


    # location / {
    #     # WebSocket用
    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection "upgrade";

    #     # 長時間接続向け
    #     proxy_read_timeout 3600s;
    #     proxy_send_timeout 3600s;

    #     proxy_pass http://127.0.0.1:3333;
    # }

    # location /vscode/ {
    #     # WebSocket用
    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection "upgrade";

    #     # 長時間接続向け
    #     proxy_read_timeout 3600s;
    #     proxy_send_timeout 3600s;

    #     proxy_pass http://127.0.0.1:3334;
    # }

    location /mybox/ {
        proxy_pass http://127.0.0.1:1111;
    }
}
